# build image ...
# docker stop jupyter
# docker rm jupyter
# docker rmi jupyter/minimal-notebook:python-3.8.8-podman
# docker image build -t jupyter/minimal-notebook:python-3.8.8-podman -f Dockerfile.lab . --no-cache
# docker run -d -it --name jupyter -p 8888:8888 -d jupyter/minimal-notebook:python-3.8.8-podman
FROM jupyter/minimal-notebook:python-3.8.8

RUN python3 -m pip install jupyterhub==3.1.1

