FROM nvcr.io/nvidia/pytorch:20.11-py3

#RUN python3 -m pip install pip==21.2.2
#RUN python3 -m pip install notebook==6.0.2
#RUN python3 -m pip install nbformat==5.1.3
#RUN python3 -m pip install nbconvert==5.6.0
#RUN python3 -m pip install nbclient==0.5.3
#RUN python3 -m pip install tornado==6.0.3
#RUN python3 -m pip install jupyter_client==6.1.12
#RUN python3 -m pip install jupyter-core==4.6.1
RUN python3 -m pip install jupyterhub==1.0.0
#RUN python3 -m pip install jupyterlab==1.2.3
#RUN python3 -m pip install jupyterlab-server==1.0.6
#RUN python3 -m pip install ldap3==2.7
RUN python3 -m pip install mecab-python3==1.0.1 ipadic fugashi
RUN python3 -m pip uninstall -y tensorboard nvidia-tensorboard nvidia-tensorboard-plugin-dlprof
RUN python3 -m pip install tensorflow==2.3.0 tensorboard==2.3.0 tensorboard-plugin-wit==1.7.0

#USER root
#RUN cat /etc/lsb-release
#RUN apt update
#RUN apt install -y pciutils
RUN apt-get update
RUN apt-get install -y iputils-ping net-tools
RUN apt-get install -y mecab libmecab-dev
RUN apt-get install -y mecab-ipadic mecab-ipadic-utf8
RUN apt-get install -y libc6-dev build-essential

RUN useradd -m jovyan
ENV HOME=/home/jovyan
WORKDIR $HOME
USER jovyan

CMD ["jupyterhub-singleuser"]

